name: scope_bo
channels:
  - IDAES-PSE
  - pytorch
  - conda-forge
dependencies:
  - adjusttext=1.3.0
  - bokeh=3.4.2
  - botorch=0.5.1
  - cpuonly=2.0
  - geometric=1.1
  - gpytorch=1.8.1
  - idaes-pse=1.13.0
  - ipykernel=6.4.1
  - jupyter=1.0.0
  - matplotlib=3.5.1
  - matplotlib-inline=0.1.3
  - mordred=1.2.
  - morfeus-ml=0.7.2
  - numba=0.56.4
  - numpy=1.21.6
  - pandas=1.3.5
  - panel=1.4.5
  - pip=21.2.4
  - pyomo=6.5.0
  - python=3.9.22
  - pytorch=1.10.2
  - qcengine=0.32.0
  - rdkit=2023.03.3
  - scikit-learn=1.6.1
  - scipy=1.11.2
  - seaborn=0.11.2
  - setuptools=58.0.4
  - shap=0.40.0
  - tqdm=4.62.3
  - umap-learn=0.5.3
  - wheel=0.37.1
  - xtb-python=22.1
  - pip:
      - vendi-score==0.0.3
